steps:
  - wait: ~
    depends_on: runtests-blessed

  - group: ":arrow_right: Downstream testing"
    notify:
      - github_commit_status:
          context: "Downstream"
    steps:
      - label: ":runner: SpectreNetlistParser"
        env:
          GITHUB_SSH_KEY: ${GITHUB_SSH_KEY?}
        plugins:
          - staticfloat/ssh-agent:
              keyvars:
                - "GITHUB_SSH_KEY"
          - JuliaCI/julia#v1: ~
          - JuliaCI/julia-test#v1:
                use_ssh: true
                coverage: false
                extra_registries: ssh://git@github.com/CedarEDA/PublicRegistry.git
                package: SpectreNetlistParser
          - staticfloat/metahook:
              # TODO: Pkg.test doesn't instantiate, requires
              # https://github.com/JuliaLang/Pkg.jl/pull/3883/commits/8ab562f72806af458c816dd2f319014f8e05e5cc
              pre-command: |
                julia -e 'using Pkg; Pkg.Registry.add(url = "ssh://git@github.com/CedarEDA/PublicRegistry.git")'
                julia --project=test --check-bounds=yes -e 'using Pkg; Pkg.instantiate()'
        agents:
          os: "linux"
          arch: "x86_64"

      - label: ":runner: VerilogAParser"
        env:
          GITHUB_SSH_KEY: ${GITHUB_SSH_KEY?}
        plugins:
          - staticfloat/ssh-agent:
              keyvars:
                - "GITHUB_SSH_KEY"
          - JuliaCI/julia#v1: ~
          - JuliaCI/julia-test#v1:
                use_ssh: true
                coverage: false
                extra_registries: ssh://git@github.com/CedarEDA/PublicRegistry.git
                package: VerilogAParser
          - staticfloat/metahook:
              # TODO: Pkg.test doesn't instantiate, requires
              # https://github.com/JuliaLang/Pkg.jl/pull/3883/commits/8ab562f72806af458c816dd2f319014f8e05e5cc
              pre-command: |
                julia -e 'using Pkg; Pkg.Registry.add(url = "ssh://git@github.com/CedarEDA/PublicRegistry.git")'
                julia --project=test --check-bounds=yes -e 'using Pkg; Pkg.instantiate()'
        agents:
          os: "linux"
          arch: "x86_64"

      - label: ":runner: BSIM4"
        env:
          GITHUB_SSH_KEY: ${GITHUB_SSH_KEY?}
        plugins:
          - staticfloat/ssh-agent:
              keyvars:
                - "GITHUB_SSH_KEY"
          - JuliaCI/julia#v1: ~
          - JuliaCI/julia-test#v1:
                use_ssh: true
                run_tests: false
                extra_registries: ssh://git@github.com/CedarEDA/PublicRegistry.git
          - staticfloat/metahook:
              pre-command: |
                echo "--- Clone BSIM4"
                git clone git@github.com:JuliaComputing/BSIM4.va.git BSIM4

                echo "--- Prepare BSIM4 to use the current version of all packages for testing"
                JULIA_PKG_PRECOMPILE_AUTO=0 \
                julia --project=BSIM4/test -e 'import Pkg; Pkg.instantiate(); \
                                                           Pkg.develop(path="."); \
                                                           Pkg.develop(path="./Lexers.jl"); \
                                                           Pkg.develop(path="./SpectreNetlistParser.jl"); \
                                                           Pkg.develop(path="./VerilogAParser.jl"); \
                                                           Pkg.precompile();'
        # Until https://github.com/JuliaLang/Pkg.jl/pull/3276 is fixed, run test script manually
        # - JuliaCI/julia-test#v1:
        #       use_ssh: true
        #       extra_registries: ssh://git@github.com/CedarEDA/PublicRegistry.git
        #       package: BSIM4
        commands: |
          cd BSIM4/test
          julia --project=. runtests.jl
        agents:
          os: "linux"
          arch: "x86_64"

      - label: ":runner: CedarTestcases.jl"
        env:
          GITHUB_SSH_KEY: ${GITHUB_SSH_KEY?}
        plugins:
          - staticfloat/ssh-agent:
              keyvars:
                - "GITHUB_SSH_KEY"
        commands: |
          echo "--- Clone CedarTestcases.jl"
          git clone git@github.com:JuliaComputing/CedarTestcases.jl.git CedarTestcases.jl

          # Bootstrap the CedarTestcases dynamic job list
          cd CedarTestcases.jl
          buildkite-agent pipeline upload .buildkite/pipeline.yml
        agents:
          os: "linux"
          arch: "x86_64"
