steps:
  - label: ":rocket: launch pipelines"
    plugins:
      - staticfloat/ssh-agent:
          keyvars:
            - "GITHUB_SSH_KEY"
      - staticfloat/cryptic#v2:
          signed_pipelines:
            - pipeline: .buildkite/build_julia.yml
              signature_file: .buildkite/build_julia.yml.signature
            - pipeline: .buildkite/docs.yml
              signature_file: .buildkite/docs.yml.signature
          unsigned_pipelines:
            - .buildkite/downstream.yml
            - .buildkite/cedar_tests.yml
    env:
      GITHUB_SSH_KEY: ${GITHUB_SSH_KEY?}
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    command: true
    agents:
      cryptic_capable: true
      os: linux
