steps:
  - label: ":julia: Run tests on 1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.7-nightly
      - JuliaCI/julia-test#v1:
          use_ssh: true
          extra_registries: https://github.com/JuliaComputing/JuliaSimRegistry
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 120
    artifact_paths:
      - "test/logs/*.pdf"
